server:
  port: 8082

spring:
  application:
    name: Greet-Api1
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_ADDRESS:http://localhost:1111/}

management:
  endpoints:
    web:
      exposure:
        include: '*'